"""
Configuration, Constants, Enums, and Data Classes for the AMT Trading Bot.

This module contains all configuration settings, constants, enumeration types,
and data classes used throughout the trading bot system.

Author: AMT Trading Bot
Version: 1.0.0
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Dict, List, Optional, Tuple, Any
from datetime import datetime, time, timezone
import os


# =============================================================================
# ENUMERATIONS
# =============================================================================

class SignalType(Enum):
    """Types of trading signals generated by the bot."""
    BREAKOUT_LONG = auto()
    BREAKOUT_SHORT = auto()
    REJECTION_LONG = auto()
    REJECTION_SHORT = auto()
    DIVERGENCE_LONG = auto()
    DIVERGENCE_SHORT = auto()
    NO_SIGNAL = auto()


class MarketCondition(Enum):
    """Current market condition classification."""
    TRENDING_UP = auto()
    TRENDING_DOWN = auto()
    RANGING = auto()
    HIGH_VOLATILITY = auto()
    LOW_VOLATILITY = auto()
    UNKNOWN = auto()


class SessionType(Enum):
    """Trading session types."""
    PRE_MARKET = auto()
    REGULAR = auto()
    POST_MARKET = auto()
    OVERNIGHT = auto()
    CLOSED = auto()


class TrendDirection(Enum):
    """Trend direction classification."""
    BULLISH = auto()
    BEARISH = auto()
    NEUTRAL = auto()


class PositionSide(Enum):
    """Position side for trades."""
    LONG = auto()
    SHORT = auto()
    FLAT = auto()


class OrderType(Enum):
    """Order types supported by the bot."""
    MARKET = auto()
    LIMIT = auto()
    STOP = auto()
    STOP_LIMIT = auto()


class TimeFrame(Enum):
    """Supported timeframes for analysis."""
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"


class RiskLevel(Enum):
    """Risk level classification."""
    LOW = auto()
    MEDIUM = auto()
    HIGH = auto()
    EXTREME = auto()


class BotMode(Enum):
    """
    Bot execution mode controlling what actions are taken.

    ANALYSIS_ONLY: Only perform market analysis, no webhook dispatch.
                   This is the safest mode for development and testing.

    TRADINGVIEW_PAPER: Send signals to TradingView webhook for paper trading.
                       Webhook dispatch is enabled but actual trading depends
                       on TradingView's paper trading configuration.
    """
    ANALYSIS_ONLY = "analysis_only"
    TRADINGVIEW_PAPER = "tradingview_paper"

    def allows_webhook(self) -> bool:
        """Check if this mode allows webhook dispatch."""
        return self == BotMode.TRADINGVIEW_PAPER

    def __str__(self) -> str:
        return self.value


# =============================================================================
# DATA CLASSES - Market Data
# =============================================================================

@dataclass
class OHLCV:
    """Open, High, Low, Close, Volume data structure."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    @property
    def range(self) -> float:
        """Calculate the candle range."""
        return self.high - self.low

    @property
    def body(self) -> float:
        """Calculate the candle body size."""
        return abs(self.close - self.open)

    @property
    def is_bullish(self) -> bool:
        """Check if candle is bullish."""
        return self.close > self.open

    @property
    def is_bearish(self) -> bool:
        """Check if candle is bearish."""
        return self.close < self.open


@dataclass
class TickData:
    """Individual tick data structure."""
    timestamp: datetime
    price: float
    volume: float
    side: str  # 'buy' or 'sell'


@dataclass
class OrderBookLevel:
    """Single level in the order book."""
    price: float
    size: float
    order_count: int = 1


@dataclass
class OrderBook:
    """Order book snapshot."""
    timestamp: datetime
    bids: List[OrderBookLevel] = field(default_factory=list)
    asks: List[OrderBookLevel] = field(default_factory=list)

    @property
    def best_bid(self) -> Optional[float]:
        """Get the best bid price."""
        return self.bids[0].price if self.bids else None

    @property
    def best_ask(self) -> Optional[float]:
        """Get the best ask price."""
        return self.asks[0].price if self.asks else None

    @property
    def spread(self) -> Optional[float]:
        """Calculate the bid-ask spread."""
        if self.best_bid and self.best_ask:
            return self.best_ask - self.best_bid
        return None

    @property
    def mid_price(self) -> Optional[float]:
        """Calculate the mid price."""
        if self.best_bid and self.best_ask:
            return (self.best_bid + self.best_ask) / 2
        return None


# =============================================================================
# DATA CLASSES - Market Structure (AMT)
# =============================================================================

@dataclass
class TPOProfile:
    """Time Price Opportunity profile data."""
    timestamp: datetime
    price_levels: Dict[float, int] = field(default_factory=dict)  # price -> TPO count
    poc: float = 0.0  # Point of Control
    val: float = 0.0  # Value Area Low
    vah: float = 0.0  # Value Area High
    initial_balance_high: float = 0.0
    initial_balance_low: float = 0.0

    @property
    def value_area_range(self) -> float:
        """Calculate the value area range."""
        return self.vah - self.val


@dataclass
class FairValueArea:
    """Fair Value Area data structure."""
    vah: float  # Value Area High
    val: float  # Value Area Low
    poc: float  # Point of Control
    developing: bool = True  # Is this a developing or settled VA

    @property
    def midpoint(self) -> float:
        """Calculate the midpoint of the value area."""
        return (self.vah + self.val) / 2

    @property
    def range(self) -> float:
        """Calculate the value area range."""
        return self.vah - self.val

    def is_price_above(self, price: float) -> bool:
        """Check if price is above the value area."""
        return price > self.vah

    def is_price_below(self, price: float) -> bool:
        """Check if price is below the value area."""
        return price < self.val

    def is_price_within(self, price: float) -> bool:
        """Check if price is within the value area."""
        return self.val <= price <= self.vah


@dataclass
class VolumeProfile:
    """Volume profile data structure."""
    price_levels: Dict[float, float] = field(default_factory=dict)  # price -> volume
    poc: float = 0.0  # Point of Control (highest volume price)
    hvn: List[float] = field(default_factory=list)  # High Volume Nodes
    lvn: List[float] = field(default_factory=list)  # Low Volume Nodes

    @property
    def total_volume(self) -> float:
        """Calculate total volume in profile."""
        return sum(self.price_levels.values())


@dataclass
class MarketStructure:
    """Complete market structure analysis result."""
    timestamp: datetime
    fva: FairValueArea
    tpo_profile: TPOProfile
    volume_profile: VolumeProfile
    current_price: float
    condition: MarketCondition
    trend: TrendDirection
    is_breakout: bool = False
    breakout_direction: Optional[TrendDirection] = None
    is_rejection: bool = False
    rejection_level: Optional[float] = None
    support_levels: List[float] = field(default_factory=list)
    resistance_levels: List[float] = field(default_factory=list)


# =============================================================================
# DATA CLASSES - Order Flow
# =============================================================================

@dataclass
class DeltaData:
    """Delta (buy volume - sell volume) data."""
    timestamp: datetime
    delta: float
    cumulative_delta: float
    buy_volume: float
    sell_volume: float
    total_volume: float

    @property
    def delta_percent(self) -> float:
        """Calculate delta as percentage of total volume."""
        if self.total_volume > 0:
            return (self.delta / self.total_volume) * 100
        return 0.0


@dataclass
class OrderFlowAnalysis:
    """Complete order flow analysis result."""
    timestamp: datetime
    delta: DeltaData
    bid_volume: float
    ask_volume: float
    imbalance_ratio: float
    aggressive_buying: bool
    aggressive_selling: bool
    absorption_detected: bool
    divergence_detected: bool
    divergence_type: Optional[str] = None  # 'bullish' or 'bearish'
    breakout_quality: float = 0.0  # 0-100 score
    liquidity_score: float = 0.0  # 0-100 score


# =============================================================================
# DATA CLASSES - Technical Indicators
# =============================================================================

@dataclass
class RSIData:
    """RSI indicator data."""
    value: float
    is_overbought: bool
    is_oversold: bool
    divergence: Optional[str] = None  # 'bullish' or 'bearish'


@dataclass
class MACDData:
    """MACD indicator data."""
    macd_line: float
    signal_line: float
    histogram: float
    is_bullish: bool
    crossover: Optional[str] = None  # 'bullish' or 'bearish'


@dataclass
class BollingerBands:
    """Bollinger Bands indicator data."""
    upper: float
    middle: float
    lower: float
    bandwidth: float
    percent_b: float
    squeeze: bool


@dataclass
class StochasticData:
    """Stochastic oscillator data."""
    k: float
    d: float
    is_overbought: bool
    is_oversold: bool
    crossover: Optional[str] = None


@dataclass
class IndicatorSet:
    """Complete set of technical indicators."""
    timestamp: datetime
    rsi: RSIData
    macd: MACDData
    bollinger: BollingerBands
    atr: float
    stochastic: StochasticData
    trend_strength: float  # 0-100


# =============================================================================
# DATA CLASSES - Correlation Analysis
# =============================================================================

@dataclass
class CorrelationData:
    """Correlation analysis between assets."""
    asset1: str
    asset2: str
    correlation: float
    rolling_correlation: float
    divergence_detected: bool
    correlation_regime: str  # 'positive', 'negative', 'neutral'


@dataclass
class MarketBreadth:
    """Market breadth indicators."""
    timestamp: datetime
    advance_decline_ratio: float
    advance_decline_line: float
    new_highs: int
    new_lows: int
    percent_above_50ma: float
    percent_above_200ma: float
    mcclellan_oscillator: float
    breadth_thrust: float

    @property
    def breadth_score(self) -> float:
        """Calculate overall breadth score (0-100)."""
        score = 50.0

        # AD ratio contribution
        if self.advance_decline_ratio > 2:
            score += 15
        elif self.advance_decline_ratio > 1:
            score += 10
        elif self.advance_decline_ratio < 0.5:
            score -= 15
        elif self.advance_decline_ratio < 1:
            score -= 10

        # MA contribution
        score += (self.percent_above_50ma - 50) * 0.3
        score += (self.percent_above_200ma - 50) * 0.2

        return max(0, min(100, score))


@dataclass
class Mag7Analysis:
    """Magnificent 7 stocks analysis."""
    timestamp: datetime
    stocks: Dict[str, float] = field(default_factory=dict)  # symbol -> performance
    average_performance: float = 0.0
    confirmation_score: float = 0.0  # -100 to 100
    divergence_from_index: float = 0.0
    leadership_score: float = 0.0


@dataclass
class VIXAnalysis:
    """VIX analysis data."""
    timestamp: datetime
    current_level: float
    percentile_rank: float  # 0-100, where current VIX sits historically
    term_structure: str  # 'contango', 'backwardation', 'flat'
    is_elevated: bool
    is_diverging: bool
    divergence_type: Optional[str] = None  # 'bullish' or 'bearish'


@dataclass
class CorrelationAnalysisResult:
    """Complete correlation analysis result."""
    timestamp: datetime
    mag7: Mag7Analysis
    vix: VIXAnalysis
    breadth: MarketBreadth
    sector_rotation: Dict[str, float] = field(default_factory=dict)
    intermarket_signals: Dict[str, str] = field(default_factory=dict)
    market_health_score: float = 0.0  # 0-100


# =============================================================================
# DATA CLASSES - Risk Management
# =============================================================================

@dataclass
class PositionSize:
    """Position sizing calculation result."""
    shares: int
    dollar_amount: float
    risk_amount: float
    percent_of_account: float
    margin_required: float


@dataclass
class TradeValidation:
    """Trade validation result."""
    is_valid: bool
    reasons: List[str] = field(default_factory=list)
    risk_score: float = 0.0  # 0-100, higher is riskier
    warnings: List[str] = field(default_factory=list)


@dataclass
class RiskMetrics:
    """Portfolio risk metrics."""
    timestamp: datetime
    total_exposure: float
    long_exposure: float
    short_exposure: float
    net_exposure: float
    gross_exposure: float
    var_95: float  # Value at Risk 95%
    var_99: float  # Value at Risk 99%
    max_drawdown: float
    current_drawdown: float
    sharpe_ratio: float
    sortino_ratio: float
    win_rate: float
    profit_factor: float


# =============================================================================
# DATA CLASSES - Trading Signals and Trades
# =============================================================================

@dataclass
class TradingSignal:
    """Trading signal generated by the strategy."""
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    direction: PositionSide
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float  # 0-100
    position_size: Optional[PositionSize] = None
    rationale: str = ""
    indicators_aligned: int = 0
    total_indicators: int = 0

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate the risk-reward ratio."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk > 0:
            return reward / risk
        return 0.0

    def to_signal(self, timeframe: str) -> Optional["Signal"]:
        """
        Convert TradingSignal to standardized Signal for webhook output.

        This method transforms the internal TradingSignal format into
        the standardized Signal format suitable for TradingView webhooks
        and other external integrations.

        Args:
            timeframe: Timeframe string (e.g., "15m", "1h") from StrategyConfig.

        Returns:
            Signal instance or None if this is a NO_SIGNAL or FLAT direction.

        Example:
            >>> signal = trading_signal.to_signal("15m")
            >>> if signal:
            ...     print(signal.to_json())
        """
        # Import here to avoid circular dependency
        from signal import Signal as WebhookSignal

        # Return None for NO_SIGNAL
        if self.signal_type == SignalType.NO_SIGNAL:
            return None

        # Determine side from direction
        if self.direction == PositionSide.LONG:
            side = "LONG"
        elif self.direction == PositionSide.SHORT:
            side = "SHORT"
        else:
            return None  # FLAT direction cannot produce a Signal

        # Extract base signal type (remove _LONG/_SHORT suffix)
        signal_type_name = self.signal_type.name
        if signal_type_name.startswith("BREAKOUT"):
            base_type = "BREAKOUT"
        elif signal_type_name.startswith("REJECTION"):
            base_type = "REJECTION"
        elif signal_type_name.startswith("DIVERGENCE"):
            base_type = "DIVERGENCE"
        else:
            return None  # Unknown signal type

        # Calculate multiple targets from single take_profit
        targets = self._calculate_multi_targets()

        # Normalize confidence from 0-100 to 0.0-1.0
        normalized_confidence = min(1.0, max(0.0, self.confidence / 100.0))

        # Format timestamp as UTC ISO string
        if self.timestamp.tzinfo is None:
            # Assume UTC if no timezone info
            timestamp_str = self.timestamp.replace(tzinfo=timezone.utc).isoformat()
        else:
            timestamp_str = self.timestamp.astimezone(timezone.utc).isoformat()

        return WebhookSignal(
            symbol=self.symbol,
            timeframe=timeframe,
            side=side,
            entry_price=round(self.entry_price, 2),
            stop_loss=round(self.stop_loss, 2),
            targets=targets,
            signal_type=base_type,
            confidence=round(normalized_confidence, 4),
            timestamp=timestamp_str,
        )

    def _calculate_multi_targets(self) -> List[float]:
        """
        Calculate multiple take-profit targets from single take_profit.

        Uses a tiered approach for scaling out positions:
        - Target 1: 50% of the way to original take_profit (conservative)
        - Target 2: Original take_profit (primary target)
        - Target 3: 150% of the distance (extended/runner)

        Returns:
            List of 3 target prices, sorted appropriately for direction.
        """
        if self.direction == PositionSide.LONG:
            distance = self.take_profit - self.entry_price
            target_1 = round(self.entry_price + distance * 0.5, 2)
            target_2 = round(self.take_profit, 2)
            target_3 = round(self.entry_price + distance * 1.5, 2)
        else:  # SHORT
            distance = self.entry_price - self.take_profit
            target_1 = round(self.entry_price - distance * 0.5, 2)
            target_2 = round(self.take_profit, 2)
            target_3 = round(self.entry_price - distance * 1.5, 2)

        return [target_1, target_2, target_3]


@dataclass
class Trade:
    """Executed trade record."""
    id: str
    timestamp: datetime
    symbol: str
    side: PositionSide
    entry_price: float
    exit_price: Optional[float] = None
    stop_loss: float = 0.0
    take_profit: float = 0.0
    quantity: int = 0
    status: str = "open"  # 'open', 'closed', 'cancelled'
    pnl: float = 0.0
    pnl_percent: float = 0.0
    exit_reason: Optional[str] = None
    signal: Optional[TradingSignal] = None

    @property
    def is_winner(self) -> bool:
        """Check if trade was profitable."""
        return self.pnl > 0


@dataclass
class Position:
    """Current position information."""
    symbol: str
    side: PositionSide
    quantity: int
    entry_price: float
    current_price: float
    stop_loss: float
    take_profit: float
    unrealized_pnl: float = 0.0
    unrealized_pnl_percent: float = 0.0

    def update_pnl(self, current_price: float):
        """Update unrealized P&L."""
        self.current_price = current_price
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (current_price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - current_price) * self.quantity

        if self.entry_price > 0:
            self.unrealized_pnl_percent = (self.unrealized_pnl / (self.entry_price * self.quantity)) * 100


# =============================================================================
# DATA CLASSES - Account and Session
# =============================================================================

@dataclass
class AccountInfo:
    """Trading account information."""
    account_id: str
    balance: float
    equity: float
    margin_used: float
    margin_available: float
    unrealized_pnl: float
    realized_pnl: float
    positions: List[Position] = field(default_factory=list)

    @property
    def total_pnl(self) -> float:
        """Calculate total P&L."""
        return self.unrealized_pnl + self.realized_pnl


@dataclass
class SessionStats:
    """Trading session statistics."""
    session_date: datetime
    session_type: SessionType
    trades_taken: int = 0
    winners: int = 0
    losers: int = 0
    gross_pnl: float = 0.0
    net_pnl: float = 0.0
    commissions: float = 0.0
    max_drawdown: float = 0.0

    @property
    def win_rate(self) -> float:
        """Calculate win rate."""
        if self.trades_taken > 0:
            return (self.winners / self.trades_taken) * 100
        return 0.0


# =============================================================================
# CONFIGURATION CLASSES
# =============================================================================

@dataclass
class RiskConfig:
    """Risk management configuration."""
    max_position_size_percent: float = 5.0  # Max % of account per position
    max_daily_loss_percent: float = 2.0  # Max daily loss as % of account
    max_total_exposure_percent: float = 100.0  # Max total exposure
    max_single_trade_risk_percent: float = 1.0  # Max risk per trade
    min_risk_reward_ratio: float = 2.0  # Minimum R:R ratio
    max_correlated_positions: int = 3  # Max positions in correlated assets
    max_open_positions: int = 5  # Max concurrent positions
    use_trailing_stop: bool = True
    trailing_stop_atr_multiple: float = 2.0
    slippage_percent: float = 0.1  # Expected slippage
    commission_per_trade: float = 1.0  # Commission per trade


@dataclass
class IndicatorConfig:
    """Technical indicator configuration."""
    # RSI
    rsi_period: int = 14
    rsi_overbought: float = 70.0
    rsi_oversold: float = 30.0

    # MACD
    macd_fast: int = 12
    macd_slow: int = 26
    macd_signal: int = 9

    # Bollinger Bands
    bb_period: int = 20
    bb_std_dev: float = 2.0
    bb_squeeze_threshold: float = 0.05

    # ATR
    atr_period: int = 14

    # Stochastic
    stoch_k_period: int = 14
    stoch_d_period: int = 3
    stoch_overbought: float = 80.0
    stoch_oversold: float = 20.0


@dataclass
class MarketStructureConfig:
    """Market structure analysis configuration."""
    # TPO Profile
    tpo_period_minutes: int = 30
    value_area_percent: float = 70.0  # % of volume for value area

    # Volume Profile
    volume_profile_bins: int = 50
    hvn_threshold_percentile: float = 80.0
    lvn_threshold_percentile: float = 20.0

    # Breakout Detection
    breakout_threshold_atr: float = 1.5
    breakout_volume_multiple: float = 1.5

    # Rejection Detection
    rejection_wick_ratio: float = 2.0
    rejection_volume_threshold: float = 1.2


@dataclass
class OrderFlowConfig:
    """Order flow analysis configuration."""
    delta_threshold: float = 0.6  # Significant delta threshold
    imbalance_ratio_threshold: float = 2.0  # Bid/ask imbalance
    absorption_threshold: float = 0.8  # Volume absorption threshold
    divergence_lookback: int = 10  # Bars to look back for divergence
    breakout_quality_min: float = 60.0  # Min breakout quality score


@dataclass
class CorrelationConfig:
    """Correlation analysis configuration."""
    # Mag7 stocks
    mag7_symbols: List[str] = field(default_factory=lambda: [
        'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA'
    ])
    mag7_confirmation_threshold: float = 0.6

    # VIX
    vix_elevated_threshold: float = 20.0
    vix_extreme_threshold: float = 30.0

    # Correlation
    correlation_lookback: int = 20
    correlation_threshold: float = 0.7
    divergence_threshold: float = 0.3


@dataclass
class WebhookConfig:
    """TradingView webhook configuration."""
    # Webhook URL (can be set via environment variable TRADINGVIEW_WEBHOOK_URL)
    # Default: local bridge at localhost:5555, fallback to webhook.site for testing
    url: str = field(default_factory=lambda: os.environ.get("TRADINGVIEW_WEBHOOK_URL", "http://localhost:5555/webhook"))

    # Operation mode
    dry_run: bool = False  # If True, no actual HTTP requests are made

    # HTTP settings
    timeout_seconds: float = 10.0  # Request timeout
    max_retries: int = 3  # Maximum retry attempts
    retry_delay_seconds: float = 1.0  # Delay between retries
    retry_backoff_multiplier: float = 2.0  # Exponential backoff multiplier

    # Headers
    content_type: str = "application/json"

    # Validation
    validate_payload: bool = True  # Validate payload before sending

    def is_configured(self) -> bool:
        """Check if webhook URL is configured."""
        return bool(self.url and self.url.strip())


@dataclass
class StrategyConfig:
    """Strategy configuration."""
    # Signal Generation
    min_confidence: float = 60.0  # Minimum signal confidence
    min_indicators_aligned: int = 3  # Minimum aligned indicators

    # Entry Conditions
    require_volume_confirmation: bool = True
    require_trend_alignment: bool = True
    require_breadth_confirmation: bool = False

    # Signal Types Enabled
    enable_breakout_signals: bool = True
    enable_rejection_signals: bool = True
    enable_divergence_signals: bool = True

    # Timeframe
    primary_timeframe: TimeFrame = TimeFrame.M15
    confirmation_timeframe: TimeFrame = TimeFrame.H1


@dataclass
class BotConfig:
    """Main bot configuration."""
    # General
    symbol: str = "SPY"
    paper_trading: bool = True
    log_level: str = "INFO"
    data_directory: str = "./data"

    # Execution Mode (default: ANALYSIS_ONLY for safety)
    mode: BotMode = BotMode.ANALYSIS_ONLY

    # Session Times (ET)
    pre_market_start: time = field(default_factory=lambda: time(4, 0))
    market_open: time = field(default_factory=lambda: time(9, 30))
    market_close: time = field(default_factory=lambda: time(16, 0))
    post_market_end: time = field(default_factory=lambda: time(20, 0))

    # Sub-configs
    risk: RiskConfig = field(default_factory=RiskConfig)
    indicators: IndicatorConfig = field(default_factory=IndicatorConfig)
    market_structure: MarketStructureConfig = field(default_factory=MarketStructureConfig)
    order_flow: OrderFlowConfig = field(default_factory=OrderFlowConfig)
    correlation: CorrelationConfig = field(default_factory=CorrelationConfig)
    strategy: StrategyConfig = field(default_factory=StrategyConfig)
    webhook: WebhookConfig = field(default_factory=WebhookConfig)

    # Account
    initial_capital: float = 100000.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert config to dictionary."""
        return {
            'symbol': self.symbol,
            'mode': self.mode.value,
            'paper_trading': self.paper_trading,
            'log_level': self.log_level,
            'initial_capital': self.initial_capital,
            'risk': {
                'max_position_size_percent': self.risk.max_position_size_percent,
                'max_daily_loss_percent': self.risk.max_daily_loss_percent,
                'min_risk_reward_ratio': self.risk.min_risk_reward_ratio,
            },
            'strategy': {
                'min_confidence': self.strategy.min_confidence,
                'min_indicators_aligned': self.strategy.min_indicators_aligned,
            },
            'webhook': {
                'url': self.webhook.url[:20] + '...' if len(self.webhook.url) > 20 else self.webhook.url,
                'dry_run': self.webhook.dry_run,
                'timeout_seconds': self.webhook.timeout_seconds,
                'max_retries': self.webhook.max_retries,
            }
        }


# =============================================================================
# CONSTANTS
# =============================================================================

# Trading Hours (Eastern Time)
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 16
MARKET_CLOSE_MINUTE = 0

# Default Values
DEFAULT_SLIPPAGE = 0.001  # 0.1%
DEFAULT_COMMISSION = 1.0  # $1 per trade
DEFAULT_ACCOUNT_SIZE = 100000.0

# Thresholds
MIN_RISK_REWARD = 1.5
MAX_POSITION_PERCENT = 10.0
MAX_DAILY_LOSS_PERCENT = 3.0

# Signal Confidence Levels
CONFIDENCE_HIGH = 80.0
CONFIDENCE_MEDIUM = 60.0
CONFIDENCE_LOW = 40.0

# Volume Analysis
VOLUME_SPIKE_THRESHOLD = 2.0
LOW_VOLUME_THRESHOLD = 0.5

# Price Levels
PRICE_LEVEL_TOLERANCE = 0.001  # 0.1% tolerance for price levels


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_default_config() -> BotConfig:
    """
    Get the default bot configuration.

    Returns:
        BotConfig: Default configuration instance.
    """
    return BotConfig()


def load_config_from_env() -> BotConfig:
    """
    Load configuration from environment variables.

    Returns:
        BotConfig: Configuration with environment overrides.
    """
    config = get_default_config()

    # Override from environment
    if os.getenv('TRADING_SYMBOL'):
        config.symbol = os.getenv('TRADING_SYMBOL')

    if os.getenv('PAPER_TRADING'):
        config.paper_trading = os.getenv('PAPER_TRADING').lower() == 'true'

    if os.getenv('INITIAL_CAPITAL'):
        config.initial_capital = float(os.getenv('INITIAL_CAPITAL'))

    if os.getenv('LOG_LEVEL'):
        config.log_level = os.getenv('LOG_LEVEL')

    return config


def validate_config(config: BotConfig) -> Tuple[bool, List[str]]:
    """
    Validate the bot configuration.

    Args:
        config: Configuration to validate.

    Returns:
        Tuple of (is_valid, list of error messages).
    """
    errors = []

    # Validate risk settings
    if config.risk.max_position_size_percent <= 0:
        errors.append("max_position_size_percent must be positive")

    if config.risk.max_position_size_percent > 100:
        errors.append("max_position_size_percent cannot exceed 100%")

    if config.risk.min_risk_reward_ratio < 1:
        errors.append("min_risk_reward_ratio should be at least 1.0")

    # Validate strategy settings
    if config.strategy.min_confidence < 0 or config.strategy.min_confidence > 100:
        errors.append("min_confidence must be between 0 and 100")

    # Validate indicator settings
    if config.indicators.rsi_period < 2:
        errors.append("rsi_period must be at least 2")

    if config.indicators.rsi_overbought <= config.indicators.rsi_oversold:
        errors.append("rsi_overbought must be greater than rsi_oversold")

    return len(errors) == 0, errors


# =============================================================================
# MODULE EXPORTS
# =============================================================================

__all__ = [
    # Enums
    'SignalType',
    'MarketCondition',
    'SessionType',
    'TrendDirection',
    'PositionSide',
    'OrderType',
    'TimeFrame',
    'RiskLevel',
    'BotMode',

    # Data Classes - Market Data
    'OHLCV',
    'TickData',
    'OrderBookLevel',
    'OrderBook',

    # Data Classes - Market Structure
    'TPOProfile',
    'FairValueArea',
    'VolumeProfile',
    'MarketStructure',

    # Data Classes - Order Flow
    'DeltaData',
    'OrderFlowAnalysis',

    # Data Classes - Indicators
    'RSIData',
    'MACDData',
    'BollingerBands',
    'StochasticData',
    'IndicatorSet',

    # Data Classes - Correlation
    'CorrelationData',
    'MarketBreadth',
    'Mag7Analysis',
    'VIXAnalysis',
    'CorrelationAnalysisResult',

    # Data Classes - Risk
    'PositionSize',
    'TradeValidation',
    'RiskMetrics',

    # Data Classes - Trading
    'TradingSignal',
    'Trade',
    'Position',
    'AccountInfo',
    'SessionStats',

    # Configuration
    'RiskConfig',
    'IndicatorConfig',
    'MarketStructureConfig',
    'OrderFlowConfig',
    'CorrelationConfig',
    'StrategyConfig',
    'WebhookConfig',
    'BotConfig',

    # Functions
    'get_default_config',
    'load_config_from_env',
    'validate_config',

    # Constants
    'MARKET_OPEN_HOUR',
    'MARKET_OPEN_MINUTE',
    'MARKET_CLOSE_HOUR',
    'MARKET_CLOSE_MINUTE',
    'DEFAULT_SLIPPAGE',
    'DEFAULT_COMMISSION',
    'DEFAULT_ACCOUNT_SIZE',
    'MIN_RISK_REWARD',
    'MAX_POSITION_PERCENT',
    'MAX_DAILY_LOSS_PERCENT',
    'CONFIDENCE_HIGH',
    'CONFIDENCE_MEDIUM',
    'CONFIDENCE_LOW',
    'VOLUME_SPIKE_THRESHOLD',
    'LOW_VOLUME_THRESHOLD',
    'PRICE_LEVEL_TOLERANCE',
]
